### ISSUE TITLE
First checkin with basic functions

### ISSUE THREAD

**Issue by miworking** [miworking/SimpleToDo#1]
My App is complete,please review ./cc @codepathreview @codepath

Issues need to fix:
1. resolution of my gif is unbearable
2. “Done" button on soft keyboard does’t show up

Future work:
features on the extending feature list.

**Comment by nidhi1608** [comment]
Mi,

Looks great! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.
Nice job with the project, hope you found it as a helpful introduction.

Look forward to seeing you in the class! In the mean time, you may consider working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and let us know if you have any questions.

**Comment by miworking** [comment]
Hi Nidhi,

Thanks a lot for reviewing my code and for all the kindly reminders to help me get involved and started. 

I will stay tuned and update my progress here in the coming days.
Looking forward to seeing you in the class!

Cheers,

Mi Zhou
